import SubpageShell from "../../components/SubpageShell";
import OriginalAssetImage from "../../components/OriginalAssetImage";

const professionals = [
  ["Dr. Héctor Campuzano González","Cirujano Dentista UNAM · Especialidad en Ortodoncia y Ortopedia Maxilar · Diagnóstico Cefalométrico", "/assets/people/Hector.jpg", "https://vatechmexico.com/wp-content/uploads/2023/07/Hector.jpg"],
  ["Dr. Victor Pardo Juárez","Especialista en Radiología Oral y Maxilofacial · Pasantía Internacional en Tomografía Cone Beam", "/assets/people/pardo.jpg", "https://vatechmexico.com/wp-content/uploads/2023/07/pardo.jpg"],
  ["Dr. Ricardo Vázquez","Universidad Autónoma de Baja California · Miembro activo del Colegio desde 1988", "/assets/people/DrRicardoVazquez.jpg", "https://vatechmexico.com/wp-content/uploads/2023/07/DrRicardoVazquez.jpg"],
  ["Dra. Laura Díaz","Facultad de Odontología UAEM · Diagnóstico y Medicina Bucal · Asociación Dental Mexicana", "/assets/people/imag-01.jpg", "https://vatechmexico.com/wp-content/uploads/2023/07/imag-01.jpg"],
  ["Dr. Ernesto Iván Herrera Ibarra","Cirujano Dentista UdeG · Master de Endodoncia · Rehabilitación estética y cosmética dental", "/assets/people/Dr-Ernesto-Ivan-Herrera-Ibarra.jpg", "https://vatechmexico.com/wp-content/uploads/2023/07/Dr-Ernesto-Ivan-Herrera-Ibarra.jpg"],
];

export default function InstitutoPage(){
  return <SubpageShell eyebrow="INSTITUTO VATECH" title={<>Conocimiento que<br/><span>eleva la práctica.</span></>} lead="La educación continua es una parte esencial del crecimiento profesional. Instituto VATECH capacita a usuarios para aprovechar mejor sus equipos, software y soluciones tecnológicas." heroAside={<div className="training-signal"><span>LEARN</span><i/><b>∞</b><small>TRAIN · APPLY · GROW</small></div>}>
    <section id="plandetrabajo" className="content-split institute-intro"><div data-reveal><p className="eyebrow red">PLAN DE TRABAJO</p><h2>Expertos en el uso de la tecnología Vatech.</h2><OriginalAssetImage localSrc="/assets/institute/insvat.png" sourceSrc="https://vatechmexico.com/wp-content/uploads/2023/07/insvat.png" alt="Instituto VATECH" className="institute-source-logo" loading="lazy"/></div><div className="prose" data-reveal><p>El objetivo es capacitar a los usuarios para que aprovechen las soluciones Vatech de forma eficiente y mejoren su trabajo clínico mediante conocimiento aplicado.</p><OriginalAssetImage localSrc="/assets/institute/MainSupport.png" sourceSrc="https://vatechmexico.com/wp-content/uploads/2023/07/MainSupport.png" alt="Equipo de capacitación Instituto VATECH" className="institute-source-image" loading="lazy"/></div></section>
    <section id="equipo" className="faculty-section"><div className="faculty-head" data-reveal><p className="eyebrow red">EQUIPO DE PROFESIONALES</p><h2>Experiencia clínica.<br/>Conocimiento compartido.</h2></div><div className="faculty-grid">{professionals.map((p,i)=><article className="faculty-card" data-reveal key={p[0]}><div className="faculty-image"><OriginalAssetImage localSrc={p[2]} sourceSrc={p[3]} alt={p[0]} loading="lazy"/><span>0{i+1}</span></div><h3>{p[0]}</h3><p>{p[1]}</p><button type="button">Conocer perfil <span>↗</span></button></article>)}</div></section>
    <section className="learning-programs"><div className="learning-copy" data-reveal><p className="eyebrow light">COMPARTIR CONOCIMIENTO</p><h2>Webinars, cursos y capacitaciones.</h2><p>Sesiones sobre software, equipos y temas odontológicos relevantes para introducir a los médicos a tecnologías innovadoras y su uso eficiente.</p></div><div className="program-list"><a href="https://www.youtube.com/playlist?list=PLfCa7Gmnx1zREqc_Wo_MADUzKKkeFCcnj" data-reveal><span>01</span><div><small>ONLINE</small><h3>Webinars VATECH</h3><p>Implantología, endodoncia, periodoncia, ortodoncia y más.</p></div><b>↗</b></a><a href="https://www.youtube.com/playlist?list=PLfCa7Gmnx1zTbYzy3NupUXawig7fHZfLE" data-reveal><span>02</span><div><small>TRAINING</small><h3>Vatech Training</h3><p>Uso de software, herramientas y diagnóstico Cone Beam.</p></div><b>↗</b></a></div></section>
  </SubpageShell>
}
